import { ThemeProvider } from "/material-tailwind/react";
import localFont from "next/font/local";
import { IBM_Plex_Serif } from 'next/font/google';

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ['latin'], // Specify subsets if needed
  weight: ['400', '700']
});

export const metadata = {
  title: "Taylor Made Music",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexSerif.className} antialiased`}
          >
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
