import { ThemeProvider } from '/material-tailwind/react';
import localFont from 'next/font/local';
import { Open_Sans, Cormorant } from 'next/font/google';

import './globals.css';

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});
const cormorant = Cormorant({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata = {
  title: 'Taylor Made Music',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className="antialiased">{children}</body>
      </html>
    </ThemeProvider>
  );
}
